/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleJMockitGuice;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import mockit.Tested;

class AppTest {

    @Tested
    public App classUnderTest;

    @Test void appHasAGreeting() {
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
