/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleJMockitGuice;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import mockit.Expectations;
import mockit.Injectable;
import mockit.Tested;

class BillingServiceTest {

    @Tested
    public BillingService billingService;

    @Injectable
    private CreditCardProcessor processor;

    @Injectable
	private TransactionLog transactionLog;

    @Test void appHasAGreeting() {
    	// Setup 
    	final String processorAbout = "Test Processor";
    	final String transactionLogAbout = "Test Transaction Log";
    	
    	new Expectations() {
    		{
    			processor.about();
    			result = processorAbout;
    			
    			transactionLog.about();
    			result = transactionLogAbout;
    		}
    	};
    	
    	// Method under test
    	final String expectedString = String.format("Billing Service use Credit Card Process [%s], and Transaction Log: [%s]", processorAbout, transactionLogAbout);
        
    	// Verifications
    	assertEquals(expectedString, billingService.about());
    }
}
